"""getChatList — session chat-history API, plus /reply for the optional
local-model integration (see app/llm_client.py).

get_chat_list/append_chat_message have no dialogue engine behind them —
nothing there decides what an assistant message *should* say next (see
ChatMessage in app/models.py for why each turn is stored/returned as a
verbatim JSON payload rather than a fixed set of columns). generate_reply
is the one endpoint that actually calls a model.

A session with no messages yet returns an empty list, not a 404 — a brand
new session legitimately has no history until the first turn is posted.
"""

from datetime import datetime, timezone
from typing import Any, Optional

from fastapi import APIRouter, Body, Depends, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app import llm_client
from app.auth import require_api_key
from app.db import get_db
from app.models import ChatMessage

router = APIRouter(prefix="/chat", tags=["chat"], dependencies=[Depends(require_api_key)])

VALID_ROLES = {"assistant", "user"}

def _append(db: Session, session_id: str, payload: dict[str, Any]) -> ChatMessage:
    next_sequence = (
        db.execute(
            select(func.max(ChatMessage.sequence)).where(ChatMessage.session_id == session_id)
        ).scalar_one()
        or 0
    ) + 1
    row = ChatMessage(
        session_id=session_id,
        sequence=next_sequence,
        role=payload["role"],
        payload=payload,
        created_at=datetime.now(timezone.utc),
    )
    db.add(row)
    db.commit()
    return row

@router.get("/{session_id}/list")
def get_chat_list(session_id: str, db: Session = Depends(get_db)) -> JSONResponse:
    """GET /chat/{session_id}/list — full turn-by-turn history for one chat
    session, in arrival order. Each item in `data.messages` is returned
    exactly as it was posted to POST /chat/{session_id}/messages or
    generated by POST /chat/{session_id}/reply."""
    rows = db.execute(
        select(ChatMessage)
        .where(ChatMessage.session_id == session_id)
        .order_by(ChatMessage.sequence)
    ).scalars().all()

    return JSONResponse(
        {"status": "success", "data": {"messages": [row.payload for row in rows]}}
    )

@router.post("/{session_id}/messages", status_code=201)
def append_chat_message(
    session_id: str,
    payload: dict[str, Any] = Body(
        ..., description="Full message object, shaped exactly as it should appear in getChatList's messages[]."
    ),
    db: Session = Depends(get_db),
) -> JSONResponse:
    """POST /chat/{session_id}/messages — append one turn to a session. The
    body is stored verbatim and echoed back under the same envelope
    getChatList uses, so callers can render optimistically off either
    response.

    Only `role` is validated — everything else (text, chip, isPopup,
    chips[], deeplink, requiresLogin, ...) is the calling chat backend's
    concern, not this service's."""
    role = payload.get("role")
    if role not in VALID_ROLES:
        raise HTTPException(status_code=422, detail=f"payload.role must be one of {sorted(VALID_ROLES)}")

    _append(db, session_id, payload)

    return JSONResponse(
        status_code=201,
        content={"status": "success", "data": {"message": payload}},
    )

class ReplyRequest(BaseModel):
    text: str

@router.post("/{session_id}/reply", status_code=201)
def generate_reply(session_id: str, body: ReplyRequest, db: Session = Depends(get_db)) -> JSONResponse:
    """POST /chat/{session_id}/reply — the model-backed endpoint. Persists
    the traveler's message, asks the local model (app/llm_client.py) for
    the next assistant turn given this session's history, persists that
    too, and returns both new turns in getChatList's message shape.

    Never 5xxs because the model is unreachable or misbehaves — llm_client
    degrades to a whatsapp_only fallback message in that case, same as a
    human agent handoff would."""
    if not body.text.strip():
        raise HTTPException(status_code=422, detail="text must not be empty")

    prior_rows = db.execute(
        select(ChatMessage).where(ChatMessage.session_id == session_id).order_by(ChatMessage.sequence)
    ).scalars().all()
    history = [row.payload for row in prior_rows]

    user_payload = {"role": "user", "text": body.text}
    _append(db, session_id, user_payload)

    assistant_payload = llm_client.generate_reply(history, body.text)
    _append(db, session_id, assistant_payload)

    return JSONResponse(
        status_code=201,
        content={"status": "success", "data": {"messages": [user_payload, assistant_payload]}},
    )

class SendChatRequest(BaseModel):
    message: str
    chip: Optional[str] = None
    arg: Any = None

@router.post("/{session_id}/send")
def send_chat(session_id: str, body: SendChatRequest, db: Session = Depends(get_db)) -> JSONResponse:
    """POST /chat/{session_id}/send — sendChat(). For when the traveler
    tapped a chip rather than typed free text: {message, chip, arg} in
    (arg carries forward whatever that chip's `arg` was, e.g. "light" or
    {"packageId": "pkg_5gb_15d"}), the next assistant turn out — as a flat
    object under `data`, not wrapped in a messages[] list, matching how a
    chip-tap reply is meant to replace the previous turn's chips rather
    than read as a transcript.

    Unlike POST /reply's free-text `text`, the model is told explicitly
    which chip group and arg were selected (not just the display text) so
    it doesn't have to re-infer intent from a label like "🗺️ Light — maps
    & WhatsApp" alone.

    Same fallback behavior as /reply: never 5xxs, degrades to a
    whatsapp_only message if the model can't be reached."""
    if not body.message.strip():
        raise HTTPException(status_code=422, detail="message must not be empty")

    prior_rows = db.execute(
        select(ChatMessage).where(ChatMessage.session_id == session_id).order_by(ChatMessage.sequence)
    ).scalars().all()
    history = [row.payload for row in prior_rows]

    user_payload: dict[str, Any] = {"role": "user", "text": body.message}
    if body.chip is not None:
        user_payload["chip"] = body.chip
    if body.arg is not None:
        user_payload["arg"] = body.arg
    _append(db, session_id, user_payload)

    llm_input = body.message
    if body.chip is not None:
        llm_input = f"[selected chip={body.chip!r} arg={body.arg!r}] {body.message}"
    assistant_payload = llm_client.generate_reply(history, llm_input)
    _append(db, session_id, assistant_payload)

    return JSONResponse(
        status_code=201,
        content={"status": "success", "data": assistant_payload},
    )
